---
# defaults file for ansible-role-configure-php-ini

# php version is generally defined according to debian distribution
# but can be forced with th following variable
# php_ini_php_version: 8.0

# Full path to cli/php.ini file
cli_php_ini_path: /etc/php/{{ php_ini_php_version_dist }}/cli/php.ini

# List of CLI PHP parameters to configure
cli_php_ini_parameters_and_values:
- parameter: post_max_size
  value: 1G
- parameter: upload_max_filesize
  value: 1G
- parameter: max_execution_time
  value: 90
- parameter: max_input_time
  value: 90
- parameter: memory_limit
  value: 256M
- parameter: date.timezone
  value: '"America/Montevideo"'


# Full path to apache2/php.ini file
apache_php_ini_path: /etc/php/{{ php_ini_php_version_dist }}/apache2/php.ini

# List of APACHE PHP parameters to configure
apache_php_ini_parameters_and_values:
- parameter: post_max_size
  value: 256M
- parameter: upload_max_filesize
  value: 256M
- parameter: max_execution_time
  value: 90
- parameter: max_input_time
  value: 90
- parameter: memory_limit
  value: 128M
- parameter: date.timezone
  value: '"America/Montevideo"'

...
